Repository baynezy/Xunit.OpenCategories, pull requests merged in 2025-03, with the labels that each got.

#107 Fix PR builds not running properly for forks
  .github/workflows/pr.yml
  .github/workflows/step-build.yml
  CHANGELOG.md
Labels: 1 min review

#102 Add a new attribute "Services"
  CHANGELOG.md
  README.md
  src/Xunit.OpenCategories.V3/ServicesAttribute.cs
  test/Xunit.OpenCategories.UnitTests.V3/ServicesAttributeTests.cs
Labels: 5 min review

#118 Release version 2.1.0.8
  CHANGELOG.md
  README.md
  semver.json
  src/Xunit.OpenCategories.V3/ServicesAttribute.cs
  src/Xunit.OpenCategories/Xunit.OpenCategories.csproj
  test/Xunit.OpenCategories.UnitTests.V3/ServicesAttributeTests.cs
  test/Xunit.OpenCategories.UnitTests.V3/Xunit.OpenCategories.UnitTests.V3.csproj
  test/Xunit.OpenCategories.UnitTests/Xunit.OpenCategories.UnitTests.csproj
Labels: 10 min review

#119 Merge master into develop branch
  CHANGELOG.md
  semver.json
Labels: 1 min review
